services:
  backend:
    build: ./backend
    volumes:
      - ./.env:/app/.env:ro
      - ./backend:/app
      - /app/__pycache__
      - /app/app/__pycache__
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  temp_storage:
