services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30m
      timeout: 30s
      retries: 3

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - backend

volumes:
  temp_storage:
